devices:
  - id: crac_01
    type: crac
    proto: modbus
    host: 10.0.10.21
    port: 502
    rack: R12
    site: dc1
    poll_interval: 10
    map: crac_standard
  - id: pdu_a1
    type: pdu
    proto: snmp
    host: 10.0.20.15
    rack: R13
    site: dc1
    poll_interval: 15
    community: private
    map: pdu_apc
  - id: poseidon_2250
    type: sensor_gateway
    proto: snmp
    host: 10.0.0.31
    rack: Poseidon
    site: dc1
    poll_interval: 15
    community: public
    map: poseidon_2250
maps:
  crac_standard:
    control:
      registers:
        supply_temp_c:
          type: holding
          address: 40010
          scale: 10
          write: true
        fan_rpm:
          type: holding
          address: 40020
          scale: 1
          write: true
    telemetry:
      temp_c:
        register_type: holding
        address: 40001
        scale: 10
      hum_pct:
        register_type: holding
        address: 40002
        scale: 10
      power_kw:
        register_type: holding
        address: 40003
        scale: 100
      airflow_cfm:
        register_type: holding
        address: 40004
        scale: 1
  pdu_apc:
    telemetry:
      power_kw:
        oid: "1.3.6.1.4.1.318.1.1.12.1.16.0"
        scale: 1000
      temp_c:
        oid: "1.3.6.1.4.1.318.1.1.26.8.3.2.1.3.1"
        scale: 10
  poseidon_2250:
    telemetry:
      sistem_oda_nem:
        oid: "1.3.6.1.4.1.21796.4.1.5447"
        scale: 10
      ag_oda_nem:
        oid: "1.3.6.1.4.1.21796.4.1.35516"
        scale: 10
      ag_oda_isi:
        oid: "1.3.6.1.4.1.21796.4.1.50338"
        scale: 10
      sistem_oda_isi:
        oid: "1.3.6.1.4.1.21796.4.1.11256"
        scale: 10
      sistem_su_baskini:
        oid: "1.3.6.1.4.1.21796.4.1.1"
        scale: 1
      sunucu_su_baskini:
        oid: "1.3.6.1.4.1.21796.4.1.2"
        scale: 1
      comm_monitor:
        oid: "1.3.6.1.4.1.21796.4.1.123"
        scale: 1
